### PR TITLE
Upload SARIF only when defects are reported

### PR DESCRIPTION
**Pull request by jamacku**
Related: https://github.com/csutils/csdiff/issues/102

### CODE REVIEW

**Review by praiskup — APPROVED** [review]
Thank you!

**Comment by praiskup** [comment]
Well, actually I think that we should do this `always()` - because otherwise, the GitHub UI doesn't hide the obsoleted issues.

**Comment by praiskup** [comment]
@jamacku could I (or you) revert?

**Comment by praiskup** [comment]
Current behavior:
Screenshot_20230206_100748
Desired behavior:
Screenshot_20230206_101041

**Comment by jamacku** [comment]
@praiskup, you are right. We should upload SARIF `always()`. Hopefully, https://github.com/csutils/csdiff/issues/102 is now fixed.

**Pull request merged**
